export const POKEMONS = [
  {
    id: 1,
    qtt: 0,
    name: "Bulbizarre",
    hp: 25,
    cp: 5,
    picture:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png",
    types: ["Plante", "Poison"],
    created: new Date(),
    prix: 500,
  },
  {
    qtt: 0,
    id: 2,
    name: "Salamèche",
    hp: 28,
    cp: 6,
    picture:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/004.png",
    types: ["Feu"],
    created: new Date(),
    prix: 300,
  },
  {
    id: 3,
    name: "Carapuce",
    qtt: 0,
    hp: 21,
    cp: 4,
    picture:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/007.png",
    types: ["Eau"],
    created: new Date(),
    prix: 450,
  },
  {
    id: 4,
    name: "Aspicot",
    hp: 16,
    cp: 2,
    picture:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/013.png",
    types: ["Insecte", "Poison"],
    qtt: 0,
    created: new Date(),
    prix: 195,
  },
  {
    id: 5,
    name: "Roucool",
    hp: 30,
    cp: 7,
    picture:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/016.png",
    types: ["Normal", "Vol"],
    created: new Date(),
    qtt: 0,
    prix: 265,
  },
  {
    id: 6,
    name: "Rattata",
    hp: 18,
    cp: 6,
    qtt: 0,
    picture:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/019.png",
    types: ["Normal"],
    created: new Date(),
    prix: 610,
  },
  {
    id: 7,
    name: "Piafabec",
    hp: 14,
    cp: 5,
    picture:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/021.png",
    types: ["Normal", "Vol"],
    qtt: 0,
    created: new Date(),
    prix: 425,
  },
  {
    id: 8,
    name: "Abo",
    hp: 16,
    cp: 4,
    picture:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/023.png",
    types: ["Poison"],
    created: new Date(),
    prix: 505,
    qtt: 0,
  },
  {
    id: 9,
    name: "Pikachu",
    hp: 21,
    cp: 7,
    picture:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/025.png",
    types: ["Electrik"],
    created: new Date(),
    prix: 520,
    qtt: 0,
  },
  {
    id: 10,
    name: "Sabelette",
    hp: 19,
    cp: 3,
    picture:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/027.png",
    qtt: 0,
    types: ["Normal"],
    created: new Date(),
    prix: 325,
  },
  {
    id: 11,
    name: "Mélofée",
    hp: 25,
    cp: 5,
    picture:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/035.png",
    types: ["Fée"],
    qtt: 0,
    created: new Date(),
    prix: 410,
  },
  {
    id: 12,
    name: "Groupix",
    hp: 17,
    cp: 8,
    picture:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/037.png",
    types: ["Feu"],
    created: new Date(),
    qtt: 0,
    prix: 275,
  },
];

export default POKEMONS;
